
cat <<EOF>>/etc/samba/smb.share.conf
[.Trash-0]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,admin,@administrators,nobody
	browseable=yes
	mediaindex=no
	hide unreadable=no
	win share=no
	enable recycle bin=no
	invalid users=nobody,nobody
	read list=nobody,nobody
	ftp disable list=no
	edit synoacl=no
	valid users=nobody,@administrators,admin,nobody
	writeable=yes
	guest ok=yes
	path=/volume2/.Trash-0
	skip smb perm=no
	comment=""
[Backup]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,nobody
	browseable=yes
	mediaindex=no
	hide unreadable=no
	win share=yes
	enable recycle bin=no
	invalid users=nobody,nobody
	read list=nobody,nobody
	ftp disable list=no
	edit synoacl=yes
	valid users=nobody,nobody
	writeable=yes
	guest ok=yes
	path=/volume2/Backup
	skip smb perm=yes
	comment=""
[homes]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,nobody
	browseable=yes
	mediaindex=no
	hide unreadable=no
	win share=yes
	enable recycle bin=no
	invalid users=nobody,nobody
	read list=nobody,nobody
	ftp disable list=no
	edit synoacl=yes
	valid users=nobody,nobody
	writeable=yes
	guest ok=yes
	path=/volume2/homes
	skip smb perm=yes
	comment="user home"
[Incoming]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,admin,@administrators,nobody
	browseable=yes
	mediaindex=no
	hide unreadable=no
	win share=no
	enable recycle bin=no
	invalid users=nobody,nobody
	read list=nobody,nobody
	ftp disable list=no
	edit synoacl=no
	valid users=nobody,@administrators,admin,nobody
	writeable=yes
	guest ok=yes
	path=/volume2/Incoming
	skip smb perm=no
	comment=""
[Partage]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,@ZALIN\Utilisateurs du domaine,nobody
	browseable=yes
	mediaindex=no
	hide unreadable=no
	win share=yes
	enable recycle bin=no
	invalid users=nobody,nobody
	read list=nobody,nobody
	ftp disable list=no
	edit synoacl=yes
	valid users=nobody,@ZALIN\Utilisateurs du domaine,nobody
	writeable=yes
	guest ok=yes
	path=/volume2/Partage
	skip smb perm=no
	comment=""
[Photo]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,admin,@administrators,nobody
	browseable=yes
	mediaindex=no
	hide unreadable=no
	win share=no
	enable recycle bin=no
	invalid users=nobody,nobody
	read list=nobody,nobody
	ftp disable list=no
	edit synoacl=no
	valid users=nobody,@administrators,admin,nobody
	writeable=yes
	guest ok=yes
	path=/volume2/Photo
	skip smb perm=no
	comment="System default shared folder"
[public]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,nobody
	browseable=yes
	mediaindex=no
	hide unreadable=no
	win share=yes
	enable recycle bin=no
	invalid users=nobody,nobody
	read list=nobody,nobody
	ftp disable list=no
	edit synoacl=yes
	valid users=nobody,nobody
	writeable=yes
	guest ok=yes
	path=/volume2/public
	skip smb perm=yes
	comment="System default shared folder"
[Video]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,@administrators,@ZALIN\Video,@ZALIN\Adultes,@ZALIN\Admins du domaine,admin,nobody
	browseable=yes
	mediaindex=no
	hide unreadable=no
	win share=no
	enable recycle bin=no
	invalid users=nobody,nobody
	read list=nobody,@ZALIN\Utilisateurs du domaine,nobody
	ftp disable list=no
	edit synoacl=no
	valid users=nobody,@ZALIN\Utilisateurs du domaine,@administrators,@ZALIN\Video,admin,@ZALIN\Adultes,@ZALIN\Admins du domaine,nobody
	writeable=yes
	guest ok=yes
	path=/volume2/Video
	skip smb perm=no
	comment="System default shared folder"
[Musique]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,@ZALIN\Utilisateurs du domaine,nobody
	browseable=yes
	mediaindex=no
	hide unreadable=no
	win share=yes
	enable recycle bin=no
	invalid users=nobody,nobody
	read list=nobody,nobody
	ftp disable list=no
	edit synoacl=yes
	valid users=nobody,@ZALIN\Utilisateurs du domaine,nobody
	writeable=yes
	guest ok=yes
	path=/volume2/Partage/Musique
	skip smb perm=no
	comment="Musique"	
EOF

sudo /usr/syno/etc/rc.sysv/S80samba.sh restart
